name: UI Tests and Allure Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install google-chrome-stable
      if: runner.os == 'Linux'

    - name: Build and Run UI Tests
      run: mvn clean install

    - name: Generate Allure Report
      run: mvn site -Dallure.results_pattern=target/allure-results

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Allure Report
      uses: actions/download-artifact@v2
      with:
        name: allure-report
        path: allure-report

    - name: Publish Allure Report
      uses: anothrNick/github-allure-action@v1
      with:
        directory: allure-report
