name: UI Tests and Allure Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Install Google Chrome
      run: |
        set -ex
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
      if: runner.os == 'Linux'

    - name: Install Xvfb
      run: |
        set -ex
        sudo apt-get install xvfb
      if: runner.os == 'Linux'

    - name: Start Xvfb
      run: |
        set -ex
        Xvfb :99 -ac -screen 0 1920x1080x16 &
        export DISPLAY=:99
      if: runner.os == 'Linux'

    - name: Build and Run UI Tests
      run: mvn clean install

    - name: Generate Allure Report
      run: mvn site -Dallure.results_pattern=target/allure-results

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Allure Report
      uses: actions/download-artifact@v2
      with:
        name: allure-report
        path: allure-report

    - name: Publish Allure Report
      uses: anothrNick/github-allure-action@v1
      with:
        directory: allure-report
